version: '3'

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8081:8081