version: '2'
services:
  web:
    build: .
    command: yarn start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - /usr/app/public
    ports:
      - '3030:8080'
  nginx:
    build: ./nginx-docker
    ports:
      - '80:80'
