# Gets Latest Node
FROM node:lts

# Creates Working App
WORKDIR /usr/src/app

# Copy's package.json file
COPY package.json ./

# Installs Dependecies for Project
RUN npm install --quiet

# Bundles source
COPY . .

#starts Project

CMD ["yarn", "dev"]

